import type { DashboardData } from "./types";

export const fallbackDashboardData: DashboardData = {
  generatedAt: "local-fallback",
  integrations: [
    {
      id: "jira",
      name: "Jira",
      mode: "read-only",
      state: "configured",
      scope: "read:account, read:jira-work",
      lastChecked: "Pending live check",
      notes: "MVP extracts issue, epic, story, and status data only.",
    },
    {
      id: "bitbucket",
      name: "Bitbucket",
      mode: "read-only",
      state: "configured",
      scope: "repository, pull request, pipeline, commit metadata",
      lastChecked: "Pending live check",
      notes: "MVP imports repository, pull request, commit, and pipeline signals.",
    },
    {
      id: "aws",
      name: "AWS CI/CD",
      mode: "mock",
      state: "unconfigured",
      scope: "CodeCommit, CodeBuild, CodePipeline placeholders",
      lastChecked: "Deferred",
      notes: "AWS is mocked until the production user and permissions are supplied.",
    },
    {
      id: "ollama",
      name: "Ollama Qwen",
      mode: "local-ai",
      state: "configured",
      scope: "qwen2.5-coder:14b, qwen3-embedding:4b",
      lastChecked: "Local runtime",
      notes: "All development AI traffic must pass through APSO AI Gateway.",
    },
  ],
  engines: [
    {
      id: "definition-gap",
      name: "Definition Gap",
      state: "ready",
      route: "POST /api/v1/engines/definition-gap/analyze",
      signal: "Missing acceptance criteria, vague stories, untestable outcomes",
      coverage: "Jira work-item analysis",
    },
    {
      id: "code-quality",
      name: "Code Quality",
      state: "ready",
      route: "POST /api/v1/engines/code-quality/analyze",
      signal: "Semgrep, tree-sitter, Gitleaks, Trivy, dependency findings",
      coverage: "Repository and branch analysis",
    },
    {
      id: "coverage",
      name: "Coverage Verification",
      state: "ready",
      route: "POST /api/v1/engines/coverage/verify",
      signal: "Traceability from Jira requirements to tests and code",
      coverage: "Work item, repository, and proof evidence",
    },
    {
      id: "release",
      name: "Release Readiness",
      state: "ready",
      route: "POST /api/v1/quality/release-readiness",
      signal: "Release blockers, risk score, unresolved quality gates",
      coverage: "Findings, pipelines, PRs, and coverage signals",
    },
  ],
  findings: [
    {
      id: "APSO-F-001",
      title: "Story lacks measurable acceptance criteria",
      severity: "high",
      source: "Definition Gap",
      status: "open",
      owner: "Product",
      evidence: "No verifiable expected outcome detected in the work item.",
    },
    {
      id: "APSO-F-002",
      title: "Security scan dependency gate is not yet wired to CI",
      severity: "medium",
      source: "Code Quality",
      status: "triaged",
      owner: "Engineering",
      evidence: "Scanner definitions exist in backend; CI invocation is pending frontend and pipeline setup.",
    },
    {
      id: "APSO-F-003",
      title: "AWS pipeline evidence unavailable",
      severity: "low",
      source: "Release Readiness",
      status: "open",
      owner: "Platform",
      evidence: "AWS remains mock-only until production credentials are supplied.",
    },
  ],
  readiness: [
    { name: "Definition Quality", score: 82, status: "watch" },
    { name: "Code Quality", score: 76, status: "watch" },
    { name: "Coverage Evidence", score: 68, status: "block" },
    { name: "Release Confidence", score: 74, status: "watch" },
  ],
  proofPackItems: [
    "Requirement quality summary",
    "AI findings and severity decisions",
    "Code quality scan evidence",
    "Coverage traceability evidence",
    "Release readiness decision record",
  ],
};
